import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SWRConfig } from "swr/_internal";
import { SWRProvider } from "./swr-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const fetcher = (url) => fetch(url).then((r) => r.json());

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <SWRProvider>
        <body className={inter.className}>{children}</body>
      </SWRProvider>
    </html>
  );
};

export default RootLayout;
