import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "./swr-provider";
import { ThemeProvider } from "@/components/ui/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <SWRProvider>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex h-[100vh] w-[100vw] dark:bg-slate-800">
              {children}
            </div>
          </ThemeProvider>
        </body>
      </SWRProvider>
    </html>
  );
};

export default RootLayout;

// <html lang="en">
//   <ThemeProvider
//     attribute="class"
//     defaultTheme="system"
//     enableSystem
//     disableTransitionOnChange
//   >
//     <SWRProvider>
//       <body className={inter.className}>{children}</body>
//     </SWRProvider>
//   </ThemeProvider>
// </html>
